version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.5
    working_directory: ~/circleci-docs
    environment:
      - LVA_Backend_ENV=production
      - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
      - JOB_RESULTS_PATH=run-results
    steps:
      - checkout
      - restore_cache:
          key: circleci-docs-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: circleci-docs-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - "vendor/bundle"
      - run:
          name: Create results directory
          command: mkdir -p $JOB_RESULTS_PATH
      - run:
          name: Expose version files
          command: |
            # cp LVA_Backend/_data/trusty/versions.json LVA_Backend/environments/trusty.json
            cp LVA_Backend/_data/trusty/versions-ubuntu-14_04-XXL.json LVA_Backend/environments/ubuntu-14.04-XXL.json
      - run:
          name: Build the LVA_Backend site
          command: bundle exec LVA_Backend build --config LVA_Backend/_config.yml,LVA_Backend/_config_production.yml --source LVA_Backend --destination LVA_Backend/_site/docs/ 2>&1 | tee $JOB_RESULTS_PATH/build-results.txt
      - run:
          name: Test with HTMLproofer
          command: bundle exec htmlproofer LVA_Backend/_site --allow-hash-href --check-favicon --check-html --disable-external --empty-alt-ignore | tee $JOB_RESULTS_PATH/htmlproofer-results.txt
      - store_artifacts: 
          path: LVA_Backend/_site/docs/
          destination: circleci-docs
      - store_artifacts: 
          path: run-results/
          destination: run-results
      - persist_to_workspace:
          root: ~/circleci-docs/LVA_Backend/_site 
          paths: 
            - docs
  deploy:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/circleci-docs  
    steps:
      - attach_workspace:
          at: ~/circleci-docs/LVA_Backend/_site 
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync LVA_Backend/_site/docs s3://circle-production-static-site/docs/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
